### ISSUE TITLE
Edit customer information doesnt update

### ISSUE THREAD

**Issue by juanobrach** [Cezerin2/cezerin2-store#12]
When you are on the customer profile and then click to edit it force you to change the password, complete all fields like shipping and billing address and then when you click on save it doesn't update.

![image](https://user-images.githubusercontent.com/7152145/53703173-63e7af80-3dd4-11e9-991a-e5a81de956df.png)

**Comment by vamcart** [comment]
Update cezerin2/cezerin2 backend.
I must to have current code from cezerin2, cezerin2-store.
And must to set 0.35.0-beta.1 for cezerin2-client in package.json in your copy of cezerin2, cezerin2-store

**Comment by vamcart** [comment]
Fixed in PR #14
