### ISSUE TITLE
Security Flaw: JWT_SECRET_KEY is accessible to user. 

### ISSUE THREAD

**Issue by LuBuss** [Cezerin2/cezerin2-store#21]
**Problem**
JWT_SECRET_KEY get compiled into a user accessible js file. The key gives admin permissions. 

config/store.js: line 15
`jwtSecretKey: process.env.JWT_SECRET_KEY || '-',`

**Comment by LuBuss** [comment]
Looking deeper into it. Newly Introduced AuthHeader does not let you remove the `JWT_SECRET_KEY` from being packed into a public js file.

**Comment by ngoyal16** [comment]
btw it should not the part of the store too

**Comment by chrisrijos** [comment]
Has this been fixed?

**Comment by vamcart** [comment]
Yes, did you see Merged badge?!
This PR merged to the current code - https://github.com/Cezerin2/cezerin2-store/pull/26
