### ISSUE TITLE
New Theme Creation Documentation

### ISSUE THREAD

**Issue by ngoyal16** [Cezerin2/cezerin2-store#3]
Is there any documentation or instructions for new theme creation/building?

**Comment by ngoyal16** [comment]
@mash12

**Comment by nntoan** [comment]
Any updates?

**Comment by vamcart** [comment]
No.

All theme files located at cezerin2-store app.
At theme folder.

Just change files and "npm run theme:build"

**Comment by nntoan** [comment]
How to create a theme then?

**Comment by ngoyal16** [comment]
we don't have document for now.. but as a guide we use theme as sub-module of cezerin2-store. please feel free to navigate around theme folder.. you can find relevant information there. and if possible please create a document too
