### ISSUE TITLE
SliderHome no loading images

### ISSUE THREAD

**Issue by LuBuss** [Cezerin2/cezerin2-store#32]
In removing the hardcoded image address from the store code, the homeSlider image bug was introduced. Currently, slider images will not show. this is because the store theme settings are stored in a static json file. 

**Solution**
Add a changeProperties method to the theme in cezerin2 that adds the asset domain and path on the api request.

**Comment by chrisrijos** [comment]
Is this ready to close? I believe you have fixed this correct?
