### ISSUE TITLE
Difference between cezerin2 and cezerin

### ISSUE THREAD

**Issue by opeoyeleke** [Cezerin2/cezerin2-store#34]
How is this different from the original cezerin project. Are there any fixes, upgrades or additions?

**Comment by ngoyal16** [comment]
cezerin2 is same as cezerin having many bug fix. we create new org because cezerin original developer are not active and not in reach too.

we made lots of change after creating org.

**Comment by vamcart** [comment]
Join our slack channel #cezerin2
