### ISSUE TITLE
folder locales

### ISSUE THREAD

**Issue by lefcf** [Cezerin2/cezerin2-store#41]
Hi guys,
I think that now files in cezerin2-store\locales\ are not used at all, so you might want to delete them.
Used are just files from cezerin2-admin\locales\.

**Comment by chrisrijos** [comment]
So there is another Feature Request for switching language based on user locale. I do not believe this is done. Also in the Locales/ folder there has been a lot of work done in translating text labels so we cannot just delete this at least for now.
