### ISSUE TITLE
Store theme

### ISSUE THREAD

**Issue by saugatpahari** [Cezerin2/cezerin2-store#55]
How can we change the theme is their any theme available for cezerin2 store.

**Comment by vamcart** [comment]
/cezerin2-store/theme folder.
You can edit theme files there.

There is no public available themes at this moment.

https://plasha.ru 

Here is the example of cezerin2 theme.

**Comment by saugatpahari** [comment]
Where do i get this theme used in plasha.ru

**Comment by vamcart** [comment]
This is commercial template and not available for free download.
