### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by Himadu2000** [Cezerin2/cezerin2-store#62]
Do this project have a slack, and do this really require twitter and Facebook ? I mean there's nothing there right ?

**Comment by vamcart** [comment]
We have telegram chat group - cezerin

https://t.me/cezerin

Slack channel also registered, but invite link is not working.

https://cezerin2.slack.com/

**Comment by vamcart** [comment]
Join cezerin group at telegram

**Comment by Himadu2000** [comment]
Done
