### ISSUE TITLE
env переменные в Cezerin2-store

### ISSUE THREAD

**Issue by vamcart** [Cezerin2/cezerin2-store#85]
Denis Deniskov, [25.05.20 15:33]
Наверное это он и есть, слушай, а ты не знаешь что делать с прокидываением process.env на клиент?

Alexander VamShop, [25.05.20 15:36]
нет, я с докером вообще дел не имел, но вот с @Pomoru как раз выяснили, что env переменные не работают в клиентском коде. и поэтому всяки текущая реализация cezerin2-docker бесполезная

Denis Deniskov, [25.05.20 15:37]
Надо просто вебпак донастроить чтобы он прокидывал нужные переменные, главное внимательно, чтобы случайно не прокинуть пароль от ДБ или секретный ключ кук

Denis Deniskov, [25.05.20 15:37]
https://webpack.js.org/plugins/environment-plugin/

**Comment by capfsb** [comment]
I think client variables need named with CLIENT_ prefix for security.

**Comment by capfsb** [comment]
fixed
